# Generated by Django 5.0.4 on 2024-06-23 18:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Attribute Name')),
                ('description', models.TextField(verbose_name='Description of the attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Skill Name')),
                ('description', models.TextField(blank=True, verbose_name='Description of the skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Experience Points')),
                ('level', models.IntegerField(default=1, verbose_name='Skill Level')),
            ],
        ),
        migrations.CreateModel(
            name='AttributeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Aggregated Total Points')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_attributes', to='leveling.attribute', verbose_name='Attribute')),
            ],
            options={
                'verbose_name': 'Attribute Level',
                'verbose_name_plural': 'Attribute Levels',
            },
        ),
    ]
