# Generated by Django 5.0.4 on 2024-06-23 18:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collective',
            name='members',
            field=models.ManyToManyField(related_name='collectives', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
    ]
