# Generated by Django 5.0.4 on 2024-06-23 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collectives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collectives.collective')),
            ],
            options={
                'verbose_name': 'Possession',
                'verbose_name_plural': 'Possessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
