# Generated by Django 5.0.4 on 2024-06-23 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artifacts', '0001_initial'),
        ('solutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaartifact',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='solutions.solution'),
        ),
    ]
