# Generated by Django 5.0.4 on 2024-06-23 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_initial'),
        ('home', '0002_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatfeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagefeed',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_feeds', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='imagefeed',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to='core.post'),
        ),
        migrations.AddField(
            model_name='imagefeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personafeed',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persona_feeds', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='personafeed',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to='core.post'),
        ),
        migrations.AddField(
            model_name='personafeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promptsfeed',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_posts', to='core.post'),
        ),
        migrations.AddField(
            model_name='promptsfeed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
