# Generated by Django 5.0.4 on 2024-06-23 17:19

import django.core.validators
import prompts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('user_achievement', 'User Achievement'), ('general', 'General'), ('bonus', 'Bonus'), ('cognition', 'Cognition'), ('mastery', 'Mastery'), ('communication', 'Communication'), ('versatility', 'Versatility'), ('discipline', 'Discipline'), ('research', 'Research')], default='general', help_text='Defines the social type of the prompts.', max_length=20)),
                ('is_forkable', models.BooleanField(default=True, help_text='Indicates if the prompts can be forked or copied.')),
                ('is_leveling', models.BooleanField(default=False, help_text='Indicates if the prompts is associated with leveling.')),
                ('engagement_type', models.CharField(help_text='Describes the nature of engagement the prompts entails.', max_length=20)),
                ('category', models.CharField(choices=prompts.models.get_category_choices, default='GEN', help_text='Categorizes the prompts for structured social.', max_length=3)),
                ('text', models.TextField(help_text='The textual content of the prompts.')),
                ('rating', models.IntegerField(default=1, help_text='Rates the prompts from 1 (lowest) to 5 (highest).', validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Records the creation time of the prompts.')),
                ('is_public', models.BooleanField(default=True, help_text='Indicates if the prompts is publicly accessible.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
