# Generated by Django 5.0.4 on 2024-06-23 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_initial'),
        ('leveling', '0002_initial'),
        ('personas', '0002_initial'),
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='author',
            field=models.ForeignKey(help_text='The user who authored the prompts.', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prompts',
            name='content_link',
            field=models.ForeignKey(blank=True, help_text='Links the prompts to specific persona content.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.personachat'),
        ),
        migrations.AddField(
            model_name='prompts',
            name='personas',
            field=models.ManyToManyField(help_text='Personas that have engaged with this prompts.', related_name='prompts', to='personas.persona'),
        ),
        migrations.AddField(
            model_name='prompts',
            name='related_skills',
            field=models.ManyToManyField(blank=True, help_text='Skills related to the prompts.', related_name='prompts', to='leveling.skill'),
        ),
    ]
