# Generated by Django 5.0.4 on 2024-06-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text content of the chat.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the chat was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the chat was last updated.')),
                ('is_public', models.BooleanField(default=False, help_text='Indicates if the chat is publicly accessible.')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The image file associated with the persona.', upload_to='persona_images/')),
                ('caption', models.TextField(blank=True, help_text='Optional caption for the image.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The date and time the image was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The date and time the image was last updated.')),
                ('is_public', models.BooleanField(default=False, help_text='Indicates if the image is publicly accessible.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
